# Generated by Django 5.2.17 on 2026-09-02 13:42

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoDeTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('nome', models.CharField(max_length=60, verbose_name='nome')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'produto de teste',
                'ordering': ('nome',),
            },
            managers=[
                ('irrestritos', django.db.models.manager.Manager()),
            ],
        ),
    ]
