"""A biblioteca de componentes do design system.

Tudo que uma tela precisa desenhar deve sair daqui. Se faltar algo, o certo é
acrescentar um componente — não escrever HTML solto numa tela, que é como o
padrão visual começa a se perder de um cliente para o outro.
"""

from .charts import Chart, DataPoint, KINDS as CHART_KINDS
from .containers import (
    Accordion,
    AccordionItem,
    ActionBar,
    Alert,
    ALINHAMENTOS,
    Box,
    Card,
    DashedButton,
    DIRECOES,
    Drawer,
    Dropdown,
    DropdownItem,
    EmptyState,
    HOSTS_DE_MAPA,
    Mapa,
    ErrorState,
    ESPACAMENTOS,
    DefinitionList,
    Fact,
    Heading,
    ItemRow,
    Modal,
    ModuleCard,
    ModuleGrid,
    PageHeader,
    SectionLabel,
    Cell,
    Slot,
    StatCard,
    Step,
    Stepper,
    Summary,
    Tab,
    Tabs,
    Timeline,
    TimelineEvent,
    Toast,
    TRANSVERSAIS,
)
from .data import Column, FilterBar, Pagination, Table
from .forms import (
    Checkbox,
    FileInput,
    Form,
    FormGrid,
    InputGroup,
    Option,
    SearchInput,
    Select,
    Textarea,
    TextInput,
)
from .permissions import Protected
from .primitives import TONES, Avatar, Badge, Button, Icon, IconButton, Pill, Raw, Spinner

__all__ = [
    "Accordion",
    "AccordionItem",
    "ActionBar",
    "Alert",
    "ALINHAMENTOS",
    "Avatar",
    "Badge",
    "Box",
    "Button",
    "Card",
    "Chart",
    "CHART_KINDS",
    "Checkbox",
    "Column",
    "DashedButton",
    "DataPoint",
    "DIRECOES",
    "Drawer",
    "Dropdown",
    "DropdownItem",
    "EmptyState",
    "HOSTS_DE_MAPA",
    "Mapa",
    "ErrorState",
    "ESPACAMENTOS",
    "FileInput",
    "FilterBar",
    "Form",
    "FormGrid",
    "Icon",
    "IconButton",
    "InputGroup",
    "DefinitionList",
    "Fact",
    "Heading",
    "ItemRow",
    "Modal",
    "ModuleCard",
    "ModuleGrid",
    "Option",
    "PageHeader",
    "Pagination",
    "Pill",
    "Protected",
    "Raw",
    "SearchInput",
    "SectionLabel",
    "Select",
    "Cell",
    "Slot",
    "Spinner",
    "StatCard",
    "Step",
    "Stepper",
    "Summary",
    "Tab",
    "Table",
    "Tabs",
    "TextInput",
    "Textarea",
    "Timeline",
    "TimelineEvent",
    "Toast",
    "TONES",
    "TRANSVERSAIS",
]
