# Generated by Django 5.2.17 on 2026-09-15 00:31

import contas.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('nome', models.SlugField(max_length=60, verbose_name='nome')),
                ('rotulo', models.CharField(max_length=120, verbose_name='rótulo')),
                ('alcance', models.CharField(choices=[('proprios', 'Os próprios'), ('filial', 'A filial'), ('empresa', 'A empresa')], default='proprios', max_length=20, verbose_name='alcance')),
                ('e_cliente', models.BooleanField(default=False, verbose_name='é cliente')),
                ('de_fabrica', models.BooleanField(default=False, verbose_name='de fábrica')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargos',
                'ordering': ('rotulo',),
            },
        ),
        migrations.CreateModel(
            name='RegistroDeAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('quando', models.DateTimeField(auto_now_add=True, verbose_name='quando')),
                ('acao', models.CharField(max_length=40, verbose_name='ação')),
                ('autor_login', models.CharField(blank=True, max_length=150, verbose_name='login do autor')),
                ('autor_nome', models.CharField(blank=True, max_length=150, verbose_name='nome do autor')),
                ('alvo', models.CharField(blank=True, max_length=255, verbose_name='alvo')),
                ('detalhe', models.CharField(blank=True, max_length=255, verbose_name='detalhe')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ('-quando',),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='telefone')),
                ('nivel', models.IntegerField(choices=[(0, 'Master'), (1, 'Titular'), (2, 'Membro')], default=2, verbose_name='nível de acesso')),
                ('idioma', models.CharField(choices=[('pt-br', 'Português'), ('es', 'Español')], default='pt-br', max_length=10, verbose_name='idioma')),
                ('avatar', models.BinaryField(blank=True, null=True, verbose_name='avatar')),
                ('avatar_tipo', models.CharField(blank=True, default='', max_length=40, verbose_name='tipo do avatar')),
                ('senha_definida_em', models.DateTimeField(blank=True, null=True, verbose_name='senha definida em')),
                ('compradores', models.ManyToManyField(blank=True, related_name='vendedores', to=settings.AUTH_USER_MODEL, verbose_name='compradores da carteira')),
                ('conta', models.ForeignKey(blank=True, db_column='conta_guid', help_text='O GUID do titular da conta desta pessoa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, to_field='guid', verbose_name='conta por GUID')),
                ('dono', models.ForeignKey(blank=True, help_text='O Admin dono da conta desta pessoa.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoas_da_conta', to=settings.AUTH_USER_MODEL, verbose_name='conta')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ('nome', 'email'),
            },
            managers=[
                ('objects', contas.models.GerenteDeUsuario()),
            ],
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('conta', models.ForeignKey(db_column='conta_guid', help_text='A conta dona desta alocação, pelo GUID do titular.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, to_field='guid', verbose_name='conta')),
            ],
            options={
                'verbose_name': 'alocação',
                'verbose_name_plural': 'alocações',
            },
        ),
    ]
