# Generated by Django 5.2.17 on 2026-09-15 00:31

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contas', '0001_initial'),
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacao',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='plataforma.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='plataforma.filial', verbose_name='filial'),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to=settings.AUTH_USER_MODEL, verbose_name='pessoa'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='conta',
            field=models.ForeignKey(db_column='conta_guid', help_text='A conta dona deste cargo, pelo GUID do titular.', on_delete=django.db.models.deletion.CASCADE, related_name='cargos_da_conta', to=settings.AUTH_USER_MODEL, to_field='guid', verbose_name='conta'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='permissoes',
            field=models.ManyToManyField(blank=True, related_name='cargos', to='auth.permission', verbose_name='permissões'),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='contas.cargo', verbose_name='cargo'),
        ),
        migrations.AddIndex(
            model_name='registrodeauditoria',
            index=models.Index(fields=['-quando'], name='idx_auditoria_quando'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='email_unico_sem_caixa', violation_error_message='Já existe alguém com este e-mail.'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(fields=('conta', 'nome'), name='cargo_unico_por_conta', violation_error_message='Já existe um cargo com este nome nesta conta.'),
        ),
        migrations.AddConstraint(
            model_name='alocacao',
            constraint=models.UniqueConstraint(condition=models.Q(('filial__isnull', False)), fields=('pessoa', 'empresa', 'filial'), name='alocacao_unica_na_filial'),
        ),
        migrations.AddConstraint(
            model_name='alocacao',
            constraint=models.UniqueConstraint(condition=models.Q(('filial__isnull', True)), fields=('pessoa', 'empresa'), name='alocacao_unica_na_empresa_inteira'),
        ),
    ]
