# Generated by Django 5.2.17 on 2026-09-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.IntegerField(choices=[(0, 'Master'), (1, 'Titular'), (2, 'Usuário')], default=2, verbose_name='nível de acesso'),
        ),
    ]
