# Generated by Django 5.2.17 on 2026-09-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_a_trilha_leva_a_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='pode_conceder',
            field=models.ManyToManyField(blank=True, related_name='concedido_por', to='contas.cargo', verbose_name='pode conceder'),
        ),
    ]
