# Generated by Django 5.2.17 on 2026-09-15 02:18

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('inicio', models.DateTimeField(verbose_name='início')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('cliente_pediu', models.BooleanField(default=False, verbose_name='cliente pediu')),
                ('resultado', models.CharField(blank=True, choices=[('vendeu', 'Vendeu'), ('nao_vendeu', 'Não vendeu')], max_length=12, verbose_name='resultado')),
                ('observacao', models.CharField(blank=True, max_length=280, verbose_name='observação')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='total')),
                ('conta', models.ForeignKey(db_column='conta_guid', help_text='A conta dona desta linha, identificada pelo GUID.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, to_field='guid', verbose_name='conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.empresa', verbose_name='empresa')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='fechado por')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.filial', verbose_name='loja')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='vendedor')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'irrestritos',
                'default_manager_name': 'irrestritos',
            },
            managers=[
                ('irrestritos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GrupoDeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('conta', models.ForeignKey(db_column='conta_guid', help_text='A conta dona desta linha, identificada pelo GUID.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, to_field='guid', verbose_name='conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'grupo de item',
                'verbose_name_plural': 'grupos de item',
                'ordering': ('ordem', 'nome'),
                'abstract': False,
                'base_manager_name': 'irrestritos',
                'default_manager_name': 'irrestritos',
            },
            managers=[
                ('irrestritos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ItemVendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fila.atendimento', verbose_name='atendimento')),
                ('conta', models.ForeignKey(db_column='conta_guid', help_text='A conta dona desta linha, identificada pelo GUID.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, to_field='guid', verbose_name='conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.empresa', verbose_name='empresa')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fila.grupodeitem', verbose_name='grupo')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'irrestritos',
                'default_manager_name': 'irrestritos',
            },
            managers=[
                ('irrestritos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MotivoDeNaoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('conta', models.ForeignKey(db_column='conta_guid', help_text='A conta dona desta linha, identificada pelo GUID.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, to_field='guid', verbose_name='conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'motivo de não venda',
                'verbose_name_plural': 'motivos de não venda',
                'ordering': ('ordem', 'nome'),
                'abstract': False,
                'base_manager_name': 'irrestritos',
                'default_manager_name': 'irrestritos',
            },
            managers=[
                ('irrestritos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='atendimento',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fila.motivodenaovenda', verbose_name='motivo'),
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('entrada', models.DateTimeField(verbose_name='entrada')),
                ('saida', models.DateTimeField(blank=True, null=True, verbose_name='saída')),
                ('conta', models.ForeignKey(db_column='conta_guid', help_text='A conta dona desta linha, identificada pelo GUID.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, to_field='guid', verbose_name='conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.empresa', verbose_name='empresa')),
                ('fechada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='fechada por')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.filial', verbose_name='loja')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='pessoa')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'irrestritos',
                'default_manager_name': 'irrestritos',
            },
            managers=[
                ('irrestritos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LugarNaFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('estado', models.CharField(choices=[('na_fila', 'Na fila'), ('atendendo', 'Atendendo'), ('em_pausa', 'Em pausa')], default='na_fila', max_length=12, verbose_name='estado')),
                ('na_fila_desde', models.DateTimeField(verbose_name='na fila desde')),
                ('desde', models.DateTimeField(verbose_name='desde')),
                ('conta', models.ForeignKey(db_column='conta_guid', help_text='A conta dona desta linha, identificada pelo GUID.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, to_field='guid', verbose_name='conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.empresa', verbose_name='empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.filial', verbose_name='loja')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='pessoa')),
                ('presenca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fila.presenca', verbose_name='presença')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'irrestritos',
                'default_manager_name': 'irrestritos',
            },
            managers=[
                ('irrestritos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='atendimento',
            name='presenca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fila.presenca', verbose_name='presença'),
        ),
        migrations.CreateModel(
            name='TipoDePausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('conta', models.ForeignKey(db_column='conta_guid', help_text='A conta dona desta linha, identificada pelo GUID.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, to_field='guid', verbose_name='conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'tipo de pausa',
                'verbose_name_plural': 'tipos de pausa',
                'ordering': ('ordem', 'nome'),
                'abstract': False,
                'base_manager_name': 'irrestritos',
                'default_manager_name': 'irrestritos',
            },
            managers=[
                ('irrestritos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Pausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('inicio', models.DateTimeField(verbose_name='início')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('conta', models.ForeignKey(db_column='conta_guid', help_text='A conta dona desta linha, identificada pelo GUID.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, to_field='guid', verbose_name='conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.empresa', verbose_name='empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.filial', verbose_name='loja')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='pessoa')),
                ('presenca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fila.presenca', verbose_name='presença')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fila.tipodepausa', verbose_name='tipo')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'irrestritos',
                'default_manager_name': 'irrestritos',
            },
            managers=[
                ('irrestritos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='grupodeitem',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('empresa'), name='fila_grupodeitem_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='itemvendido',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='fila_item_vendido_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='motivodenaovenda',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('empresa'), name='fila_motivodenaovenda_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='presenca',
            constraint=models.UniqueConstraint(condition=models.Q(('saida__isnull', True)), fields=('pessoa',), name='fila_uma_presenca_aberta_por_pessoa'),
        ),
        migrations.AddIndex(
            model_name='lugarnafila',
            index=models.Index(fields=['filial', 'estado', 'na_fila_desde'], name='fila_lugar_ordem'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['filial', 'fim'], name='fila_atendimento_do_dia'),
        ),
        migrations.AddConstraint(
            model_name='atendimento',
            constraint=models.UniqueConstraint(condition=models.Q(('fim__isnull', True)), fields=('vendedor',), name='fila_um_atendimento_aberto_por_vendedor'),
        ),
        migrations.AddConstraint(
            model_name='tipodepausa',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('empresa'), name='fila_tipodepausa_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='pausa',
            constraint=models.UniqueConstraint(condition=models.Q(('fim__isnull', True)), fields=('pessoa',), name='fila_uma_pausa_aberta_por_pessoa'),
        ),
    ]
