# Generated by Django 5.2.17 on 2026-09-15 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0001_initial'),
        ('plataforma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['empresa', 'filial', 'fim'], name='fila_atendimento_periodo'),
        ),
        migrations.AddIndex(
            model_name='pausa',
            index=models.Index(fields=['filial', 'inicio'], name='fila_pausa_periodo'),
        ),
    ]
