# Generated by Django 5.2.17 on 2026-09-15 14:11

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0002_indices_dos_indicadores'),
        ('plataforma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDeVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('mes', models.DateField(verbose_name='mês')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('alterada_em', models.DateTimeField(auto_now=True, verbose_name='alterada em')),
                ('conta', models.ForeignKey(db_column='conta_guid', help_text='A conta dona desta linha, identificada pelo GUID.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, to_field='guid', verbose_name='conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.empresa', verbose_name='empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.filial', verbose_name='loja')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='vendedor')),
            ],
            options={
                'verbose_name': 'meta de venda',
                'verbose_name_plural': 'metas de venda',
                'abstract': False,
                'base_manager_name': 'irrestritos',
                'default_manager_name': 'irrestritos',
                'constraints': [models.UniqueConstraint(condition=models.Q(('pessoa__isnull', True)), fields=('filial', 'mes'), name='fila_uma_meta_da_loja_por_mes'), models.UniqueConstraint(condition=models.Q(('pessoa__isnull', False)), fields=('filial', 'pessoa', 'mes'), name='fila_uma_meta_por_pessoa_loja_e_mes'), models.CheckConstraint(condition=models.Q(('mes__day', 1)), name='fila_meta_no_dia_1'), models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='fila_meta_positiva')],
            },
            managers=[
                ('irrestritos', django.db.models.manager.Manager()),
            ],
        ),
    ]
