# Generated by Django 5.2.17 on 2026-09-17 17:38

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0003_metas_de_venda'),
        ('plataforma', '0003_filial_por_nome_e_com_a_conta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrecaoNaFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('acao', models.CharField(choices=[('mover', 'Mudou de posição'), ('pausar', 'Pôs em pausa'), ('tirar_pausa', 'Tirou da pausa'), ('fechar', 'Fechou o atendimento'), ('tirar', 'Tirou da loja'), ('editar', 'Corrigiu o lançamento')], max_length=12, verbose_name='ação')),
                ('observacao', models.CharField(max_length=200, verbose_name='motivo')),
                ('detalhe', models.CharField(blank=True, max_length=300, verbose_name='detalhe')),
                ('momento', models.DateTimeField(verbose_name='quando')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='quem corrigiu')),
                ('conta', models.ForeignKey(db_column='conta_guid', help_text='A conta dona desta linha, identificada pelo GUID.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, to_field='guid', verbose_name='conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.empresa', verbose_name='empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.filial', verbose_name='loja')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='vendedor')),
            ],
            options={
                'verbose_name': 'correção na fila',
                'verbose_name_plural': 'correções na fila',
                'abstract': False,
                'base_manager_name': 'irrestritos',
                'default_manager_name': 'irrestritos',
                'indexes': [models.Index(fields=['filial', 'momento'], name='fila_correcao_periodo')],
            },
            managers=[
                ('irrestritos', django.db.models.manager.Manager()),
            ],
        ),
    ]
