# Generated by Django 5.2.17 on 2026-09-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0004_correcoes_na_fila'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugarnafila',
            name='estado',
            field=models.CharField(choices=[('na_fila', 'Na fila'), ('atendendo', 'Atendendo'), ('em_pausa', 'Em pausa'), ('em_espera', 'Em espera')], default='na_fila', max_length=12, verbose_name='estado'),
        ),
    ]
