# Generated by Django 5.2.17 on 2026-09-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0005_estado_em_espera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correcaonafila',
            name='acao',
            field=models.CharField(choices=[('mover', 'Mudou de posição'), ('pausar', 'Pôs em pausa'), ('tirar_pausa', 'Tirou da pausa'), ('fechar', 'Fechou o atendimento'), ('tirar', 'Tirou da loja'), ('editar', 'Corrigiu o lançamento'), ('por_na_fila', 'Pôs na fila')], max_length=12, verbose_name='ação'),
        ),
    ]
