# Generated by Django 5.2.17 on 2026-09-23 14:23

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0007_fluxo_da_empresa'),
        ('plataforma', '0006_empresa_sem_fluxo_da_fila'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoDaLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('fim', models.TimeField(verbose_name='fim do turno')),
                ('conta', models.ForeignKey(db_column='conta_guid', help_text='A conta dona desta linha, identificada pelo GUID.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, to_field='guid', verbose_name='conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.empresa', verbose_name='empresa')),
                ('filial', models.OneToOneField(help_text='A loja deste turno.', on_delete=django.db.models.deletion.CASCADE, related_name='turno', to='plataforma.filial', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'turno da loja',
                'verbose_name_plural': 'turnos das lojas',
                'abstract': False,
                'base_manager_name': 'irrestritos',
                'default_manager_name': 'irrestritos',
            },
            managers=[
                ('irrestritos', django.db.models.manager.Manager()),
            ],
        ),
    ]
