# Generated by Django 5.2.17 on 2026-09-25 15:24

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0009_supervisor_ganha_participar'),
        ('plataforma', '0006_empresa_sem_fluxo_da_fila'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('conta', models.ForeignKey(db_column='conta_guid', help_text='A conta dona desta linha, identificada pelo GUID.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, to_field='guid', verbose_name='conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'mídia',
                'verbose_name_plural': 'mídias',
                'ordering': ('ordem', 'nome'),
                'abstract': False,
                'base_manager_name': 'irrestritos',
                'default_manager_name': 'irrestritos',
            },
            managers=[
                ('irrestritos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='atendimento',
            name='midia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fila.midia', verbose_name='mídia'),
        ),
        migrations.AddConstraint(
            model_name='midia',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('empresa'), name='fila_midia_nome_unico'),
        ),
    ]
