# Generated by Django 5.2.17 on 2026-09-25 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0010_midia'),
        ('plataforma', '0006_empresa_sem_fluxo_da_fila'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pausa',
            name='fixa',
            field=models.CharField(blank=True, choices=[('administrativa', 'Administrativa'), ('gestao', 'Gestão')], max_length=16, verbose_name='pausa da gestão'),
        ),
        migrations.AlterField(
            model_name='correcaonafila',
            name='acao',
            field=models.CharField(choices=[('mover', 'Mudou de posição'), ('pausar', 'Pôs em pausa'), ('tirar_pausa', 'Tirou da pausa'), ('fechar', 'Fechou o atendimento'), ('tirar', 'Tirou da loja'), ('editar', 'Corrigiu o lançamento'), ('por_na_fila', 'Pôs na fila'), ('recolocar', 'Recolocou na fila')], max_length=12, verbose_name='ação'),
        ),
        migrations.AlterField(
            model_name='pausa',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fila.tipodepausa', verbose_name='tipo'),
        ),
        migrations.AddConstraint(
            model_name='pausa',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fixa', ''), ('tipo__isnull', False)), models.Q(('fixa__in', ['administrativa', 'gestao']), ('tipo__isnull', True)), _connector='OR'), name='fila_pausa_tipo_ou_fixa'),
        ),
    ]
