# Generated by Django 5.2.17 on 2026-09-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0011_pausas_da_gestao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correcaonafila',
            name='acao',
            field=models.CharField(choices=[('mover', 'Mudou de posição'), ('pausar', 'Pôs em pausa'), ('tirar_pausa', 'Tirou da pausa'), ('fechar', 'Fechou o atendimento'), ('tirar', 'Fechou o ponto'), ('editar', 'Corrigiu o lançamento'), ('por_na_fila', 'Pôs na fila'), ('recolocar', 'Recolocou na fila')], max_length=12, verbose_name='ação'),
        ),
    ]
