# Generated by Django 5.2.17 on 2026-09-15 00:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemDaMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('lugar', models.CharField(max_length=20, unique=True, verbose_name='lugar')),
                ('conteudo', models.BinaryField(verbose_name='conteúdo')),
                ('tipo', models.CharField(max_length=40, verbose_name='tipo')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
            ],
            options={
                'verbose_name': 'imagem da marca',
                'verbose_name_plural': 'imagens da marca',
                'ordering': ('lugar',),
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('client_name', models.CharField(max_length=120, verbose_name='nome do cliente')),
                ('system_name', models.CharField(blank=True, max_length=120, verbose_name='nome do sistema')),
                ('primary', models.CharField(default='#1e40af', max_length=9, verbose_name='cor primária')),
                ('accent', models.CharField(default='#217598', max_length=9, verbose_name='cor de destaque')),
                ('radius', models.CharField(default='6px', max_length=8, verbose_name='arredondamento')),
                ('radius_control', models.CharField(default='4px', max_length=8, verbose_name='arredondamento dos controles')),
                ('density', models.CharField(default='normal', max_length=16, verbose_name='densidade')),
                ('sidebar_width', models.CharField(default='256px', max_length=8, verbose_name='largura do menu')),
                ('shadows', models.BooleanField(default=True, verbose_name='sombras')),
                ('zebra', models.BooleanField(default=False, verbose_name='tabela listrada')),
                ('sidebar_bg', models.CharField(blank=True, default='#1f275d', max_length=9, verbose_name='fundo do menu')),
                ('sidebar_text', models.CharField(blank=True, default='#ffffff', max_length=9, verbose_name='texto do menu')),
                ('header_bg', models.CharField(blank=True, max_length=9, verbose_name='fundo do cabeçalho')),
                ('header_text', models.CharField(blank=True, max_length=9, verbose_name='texto do cabeçalho')),
                ('content_bg', models.CharField(blank=True, max_length=9, verbose_name='fundo do conteúdo')),
                ('footer_bg', models.CharField(blank=True, max_length=9, verbose_name='fundo do rodapé')),
                ('footer_text', models.CharField(blank=True, max_length=9, verbose_name='texto do rodapé')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('rotulo_da_empresa', models.CharField(blank=True, max_length=40, verbose_name='rótulo da empresa')),
                ('rotulo_da_filial', models.CharField(blank=True, max_length=40, verbose_name='rótulo da filial')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('chave', models.CharField(max_length=60, unique=True, verbose_name='chave')),
                ('ativo', models.BooleanField(default=False, verbose_name='ligado')),
                ('rotulo', models.CharField(blank=True, max_length=120, verbose_name='rótulo')),
                ('grupo', models.CharField(blank=True, max_length=120, verbose_name='grupo')),
                ('ordem', models.IntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'módulo',
                'verbose_name_plural': 'módulos',
                'ordering': ('ordem', 'chave'),
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('chave', models.CharField(max_length=60, unique=True, verbose_name='chave')),
                ('valor', models.TextField(verbose_name='valor')),
            ],
            options={
                'verbose_name': 'parâmetro',
                'verbose_name_plural': 'parâmetros',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('razao_social', models.CharField(max_length=180, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=180, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, verbose_name='inscrição estadual')),
                ('logradouro', models.CharField(blank=True, max_length=180, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=80, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=80, verbose_name='bairro')),
                ('municipio', models.CharField(blank=True, max_length=120, verbose_name='município')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('host', models.CharField(blank=True, default='', max_length=255, verbose_name='host')),
                ('porta', models.CharField(blank=True, default='', max_length=10, verbose_name='porta')),
                ('banco', models.CharField(blank=True, default='', max_length=100, verbose_name='banco')),
                ('tabela', models.CharField(blank=True, default='', max_length=100, verbose_name='tabela')),
                ('usuario', models.CharField(blank=True, default='', max_length=255, verbose_name='usuário')),
                ('senha', models.CharField(blank=True, default='', max_length=255, verbose_name='senha (cifrada)')),
                ('conta', models.ForeignKey(blank=True, db_column='conta_guid', help_text='O GUID da conta titular desta empresa.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, to_field='guid', verbose_name='conta por GUID')),
                ('dono', models.ForeignKey(blank=True, help_text='O Admin dono desta empresa.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_da_conta', to=settings.AUTH_USER_MODEL, verbose_name='conta')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ('razao_social',),
            },
        ),
        migrations.CreateModel(
            name='Falha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('quando', models.DateTimeField(auto_now_add=True, verbose_name='quando')),
                ('caminho', models.CharField(max_length=255, verbose_name='caminho')),
                ('metodo', models.CharField(max_length=10, verbose_name='método')),
                ('autor_login', models.CharField(blank=True, max_length=150, verbose_name='login do autor')),
                ('autor_nome', models.CharField(blank=True, max_length=150, verbose_name='nome do autor')),
                ('resumo', models.CharField(max_length=255, verbose_name='resumo')),
                ('traceback', models.TextField(verbose_name='traceback')),
            ],
            options={
                'verbose_name': 'falha',
                'verbose_name_plural': 'falhas',
                'ordering': ('-quando',),
                'indexes': [models.Index(fields=['-quando'], name='idx_falha_quando')],
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('apelido', models.CharField(max_length=60, verbose_name='apelido')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('logradouro', models.CharField(blank=True, max_length=180, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=80, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=80, verbose_name='bairro')),
                ('municipio', models.CharField(blank=True, max_length=120, verbose_name='município')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('ordem', models.IntegerField(default=0, verbose_name='ordem')),
                ('e_matriz', models.BooleanField(default=False, verbose_name='é a matriz')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filiais', to='plataforma.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'filial',
                'verbose_name_plural': 'filiais',
                'ordering': ('ordem', 'nome'),
            },
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(condition=models.Q(('cnpj', ''), _negated=True), fields=('cnpj',), name='cnpj_unico_por_instalacao', violation_error_message='Já existe uma empresa com este CNPJ.'),
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(condition=models.Q(('dono__isnull', False)), fields=('dono',), name='uma_empresa_por_conta', violation_error_message='Esta conta já tem uma empresa.'),
        ),
        migrations.AddConstraint(
            model_name='filial',
            constraint=models.UniqueConstraint(condition=models.Q(('e_matriz', True)), fields=('empresa',), name='uma_matriz_por_empresa'),
        ),
    ]
