# Generated by Django 5.2.17 on 2026-09-16 00:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AparenciaDaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador estável desta linha para fora do sistema.', unique=True, verbose_name='GUID')),
                ('sidebar_bg', models.CharField(blank=True, max_length=9, verbose_name='fundo do menu')),
                ('sidebar_text', models.CharField(blank=True, max_length=9, verbose_name='texto do menu')),
                ('logo', models.BinaryField(blank=True, null=True, verbose_name='logo do menu')),
                ('logo_tipo', models.CharField(blank=True, max_length=40, verbose_name='tipo do logo')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aparencia', to='plataforma.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'aparência da empresa',
                'verbose_name_plural': 'aparências das empresas',
            },
        ),
    ]
