# Generated by Django 5.2.17 on 2026-09-17 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_filial_por_nome_e_com_a_conta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='empresa',
            name='uma_empresa_por_conta',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='dono',
            field=models.ForeignKey(blank=True, help_text='O Admin dono desta empresa.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_da_conta', to=settings.AUTH_USER_MODEL, verbose_name='conta'),
        ),
    ]
