# Generated by Django 5.2.17 on 2026-09-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_varias_empresas_por_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fluxo_da_fila',
            field=models.CharField(choices=[('volta_para_a_fila', 'Volta para o fim da fila'), ('espera', 'Fica em espera e entra na fila quando quiser')], default='volta_para_a_fila', help_text='O que acontece com o vendedor depois de lançar o atendimento.', max_length=20, verbose_name='fluxo da fila'),
        ),
    ]
