"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Falha fechado de propósito, nos dois: o resto da base já segue esse
# princípio — `pode(None, x)` é `False`, `Protected` nasce com
# `allowed=False`, o menu não vaza item nenhum quando ninguém ligou a
# autenticação. Um `settings.py` que falha aberto contradiria isso.
#
# SECURITY WARNING: don't run with debug turned on in production!
# Sem DJANGO_DEBUG, o padrão é DEBUG=False — e não True. Esquecer a
# variável em produção não pode virar traceback completo com settings
# expostos na tela do cliente; o preço de esquecer é a tela de erro
# genérica do Django, não um vazamento.
DEBUG = os.environ.get("DJANGO_DEBUG", "") == "1"

# SECURITY WARNING: keep the secret key used in production secret!
# O KRONOS.net publica UMA imagem para mais de 20 VPS, cada uma com seu
# próprio banco. Uma chave fixa commitada seria compartilhada pelas vinte
# instalações — um cookie de sessão forjado numa valeria em todas. Por
# isso, fora de DEBUG, a ausência de DJANGO_SECRET_KEY não cai num
# fallback conhecido: levanta na hora. Cair em silêncio no fallback seria
# trocar "chave commitada" por "chave commitada que ninguém percebe que
# está usando" — pior, não melhor. Só em DEBUG (desenvolvimento local) o
# valor óbvio de "não confie nisto" é aceito.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY é obrigatória fora de DEBUG. A imagem é a "
            "mesma nas vinte instalações: uma chave compartilhada faz um "
            "cookie forjado numa valer em todas. Defina DJANGO_SECRET_KEY, "
            "ou DJANGO_DEBUG=1 para desenvolvimento local."
        )
    SECRET_KEY = "django-insecure-somente-para-desenvolvimento-local"

ALLOWED_HOSTS = [
    h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "nucleo",
    # `comum` antes de quem o usa: e a camada de baixo (listagem, filtros,
    # exportacao, CSRF e as guardas de rota). Nao tem model nem regra de
    # negocio — se um dia precisar importar `contas` ou `plataforma`, e
    # sinal de que aquilo nao era dele.
    "comum",
    "contas",
    "plataforma",
    # Módulos de negócio de cada SaaS entram aqui, DEPOIS da base — ver
    # `modulos/exemplo/` para a forma, e `CLAUDE.md` §2 para a regra de
    # camada: a base nunca importa um deles.
    # O negócio do Fila Zero: a fila da vez das lojas.
    "fila",
    "modulos.exemplo",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Quem serve o `/static/` coletado no build — gunicorn sozinho não
    # serve estático, e sem isto o login inteiro abria sem CSS (o defeito
    # só apareceu fora dos testes: a suíte roda com DJANGO_DEBUG=1, onde o
    # próprio Django serve estático).
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # O `SessionMiddleware` do Django com uma diferença: em `/api/` a chave
    # vem do cabeçalho `Authorization` e o cookie é ignorado — é o que torna
    # segura a isenção de CSRF das rotas do Ninja. Ver o docstring do módulo.
    "comum.sessao_por_cabecalho.MiddlewareDeSessao",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # DEPOIS da autenticação de propósito: o idioma é uma coluna da pessoa
    # (`comum/idioma.py`), e antes daqui `request.user` ainda não existe.
    "comum.idioma.MiddlewareDeIdioma",
    # O aviso de personificação da API (`X-Vendo-Como`). Depois da sessão,
    # que ele lê; antes das falhas, para o erro que sobe continuar intacto.
    "comum.aviso_na_api.MiddlewareDoVendoComo",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # O erro em produção (Bloco 7): toda exceção de view grava uma linha em
    # `plataforma.Falha` e sobe intacta. Por último: vê o que escapar de
    # todo o resto, mas DEPOIS da sessão — o autor da falha vem dela.
    "plataforma.falhas.MiddlewareDeFalhas",
]

#: Onde o erro cai: no stdout, que é o `docker logs` do VPS — o primeiro
#: lugar onde se olha. O `django.request` derruba o traceback inteiro em
#: ERROR; o resto do sistema em INFO. Nada de arquivo: em container, log
#: em disco é só um lugar a mais para esquecer de girar.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "padrao": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "padrao",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# O banco é Postgres, SEMPRE — inclusive em desenvolvimento e na suíte.
#
# Havia aqui um caminho de SQLite quando `KRONOS_BANCO` estava vazio, para
# "não exigir serviço de pé em quem só quer rodar a suíte", e o comentário
# afirmava que o esquema era o mesmo nos dois. O ESQUEMA é; o comportamento
# não — transação, `CheckConstraint`, ordenação com acento, `distinct`,
# tipo de coluna. As vinte instalações rodam Postgres, e testar noutro banco
# é provar a coisa errada.
#
# O outro custo já apareceu antes deste: com os dois caminhos vivos, a mesma
# instalação tinha DOIS bancos — cadastrava-se num e olhava-se no outro,
# porque `runserver` sem a variável caía no SQLite sem avisar.
#
# Falha fechado como a `DJANGO_SECRET_KEY` acima, e pelo mesmo motivo: a
# ausência precisa travar a subida, não escolher um caminho silencioso.
_BANCO = os.environ.get("KRONOS_BANCO", "")
if not _BANCO:
    raise ImproperlyConfigured(
        "KRONOS_BANCO é obrigatória: o KRONOS roda em Postgres em toda "
        "instalação, e desenvolvimento e testes rodam no mesmo banco de "
        "propósito. Suba o compose e exporte, por exemplo, "
        "KRONOS_BANCO=postgresql://kronos:kronos@127.0.0.1:5433/kronos "
        "(ver README)."
    )
DATABASES = {"default": dj_database_url.parse(_BANCO, conn_max_age=600)}


# --- Autenticação -----------------------------------------------------------
#
# O usuário é deste projeto, e não o `auth.User` do Django. O motivo está em
# `contas/models.py::Usuario` e na spec de 02/09: `auth_user` nasce de uma
# migração dentro do pacote do Django e não aceita coluna nova, e este produto
# precisa de cinco.
AUTH_USER_MODEL = "contas.Usuario"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Os dois estavam no padrão do `startproject` (`en-us` e `UTC`), e os dois
# apareciam na tela do cliente:
#
# 1. Toda mensagem que o DJANGO escreve saía em inglês no meio de um sistema
#    em português — "Ensure this value has at most 180 characters" quando
#    alguém colava um texto grande demais. As mensagens desta casa sempre
#    foram em português; as do framework não, e ninguém tinha reparado
#    porque só aparecem em caminho de erro.
# 2. **A trilha de auditoria mostrava a hora errada, três horas adiantada.**
#    Com `USE_TZ = True` o banco guarda em UTC (que é o certo, e não muda), e
#    é o `TIME_ZONE` que decide em que relógio a tela exibe. Em UTC, uma ação
#    das 10h aparecia como 13h — e a trilha existe justamente para responder
#    "quem fez o quê, e QUANDO".
LANGUAGE_CODE = "pt-br"

# **Os dois idiomas do produto** (09/09/2026). O portal vai ser vendido no
# Paraguai, e lá se fala castelhano — a MOLDURA do sistema (menu, botões,
# mensagens) passa a existir nos dois.
#
# O que NÃO está aqui, e é a parte que mais confunde: o catálogo em si. Nome
# de peça, família e aplicação são dado que o cliente digitou, e moram em
# linha de tabela — nenhum arquivo de tradução alcança isso. Enquanto a
# tradução do conteúdo não for feita, o paraguaio vê a moldura em espanhol e
# a peça em português, e isso é esperado, não defeito.
LANGUAGES = [
    ("pt-br", "Português"),
    ("es", "Español"),
]

#: Uma pasta só, na raiz. Os `.po` por app (o padrão do Django quando não se
#: diz nada) espalhariam a mesma frase — "Salvar", "Remover" — por seis
#: arquivos, e quem traduz teria de decidir seis vezes a mesma palavra.
LOCALE_PATHS = [BASE_DIR / "locale"]

# Vem do ambiente porque a MESMA imagem serve instalações em estados
# diferentes: Sorriso (MT) é UTC-4 e São Paulo é UTC-3, e uma constante aqui
# erraria a hora de metade delas. O padrão cobre o caso comum sem exigir que
# alguém saiba que esta variável existe.
TIME_ZONE = os.environ.get("DJANGO_TZ", "America/Sao_Paulo")

USE_I18N = True

# O banco continua em UTC. Isto NÃO é o que a tela mostra — é o que evita
# uma hora ambígua duas vezes por ano no horário de verão, e é o que faz a
# comparação entre duas instalações em fusos diferentes significar algo.
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

# `collectstatic` (rodado na construção da imagem, ver Dockerfile) precisa de
# um destino fora dos diretórios de app para juntar os estáticos de todo
# mundo. Em desenvolvimento local isso nunca é exercitado — `runserver`
# serve direto do diretório do app.
STATIC_ROOT = BASE_DIR / "staticfiles"

# --- HTTPS ------------------------------------------------------------------
#
# `manage.py check --deploy` acusava quatro coisas, e todas as quatro têm o
# mesmo desfecho: o cookie de sessão viajando em texto claro. Quem estiver na
# mesma rede Wi-Fi de quem usa o portal copia o cookie e entra como a pessoa —
# sem senha, sem aviso, sem deixar rastro diferente de um acesso normal.
#
# **Ligadas fora de DEBUG, e só lá.** Em desenvolvimento a máquina serve
# `http://127.0.0.1`, e um cookie `Secure` simplesmente não é enviado: a tela
# de entrada aceitaria a senha e devolveria a tela de entrada, para sempre,
# sem dizer por quê. É a configuração que mais parece defeito do sistema.
if not DEBUG:
    # O cookie só viaja por HTTPS. Os dois, e não só o de sessão: o token
    # CSRF em claro deixa forjar requisição em nome de quem está logado.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # `Lax` é o padrão do Django e está certo aqui — o portal não recebe POST
    # de outro site, e `Strict` quebraria o clique num link de e-mail.
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"

    # JavaScript não lê o cookie de sessão. Não é o que impede XSS; é o que
    # impede um XSS de virar sessão roubada.
    SESSION_COOKIE_HTTPONLY = True

    # Quem chegar por `http://` é mandado para `https://`. O proxy do VPS já
    # faz isso hoje, e ter nos dois lugares é de propósito: o dia em que
    # alguém trocar o proxy, a aplicação continua recusando o texto claro.
    SECURE_SSL_REDIRECT = True

    # Como o Django descobre que a requisição chegou por HTTPS quando quem
    # termina o TLS é o proxy. **Sem esta linha, `SECURE_SSL_REDIRECT` acima
    # entra em laço infinito de redirecionamento**: a aplicação vê `http`,
    # manda para `https`, o proxy entrega em `http` de novo. Só é seguro
    # porque nada além do proxy fala com o container.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # HSTS: o navegador passa a recusar `http://` neste domínio por conta
    # própria, sem nem tentar. Um ano, o valor que a própria lista de
    # pré-carga do Chrome exige.
    #
    # **É a única linha aqui que não se desfaz mudando o código.** O navegador
    # de quem já visitou guarda a regra pelo prazo inteiro: se o domínio
    # precisar voltar a servir HTTP, essas pessoas ficam sem acesso até o
    # prazo vencer. Por isso o subdomínio fica de fora — ligar
    # `INCLUDE_SUBDOMAINS` sem certificado em todos os subdomínios derruba os
    # que ainda não têm.
    SECURE_HSTS_SECONDS = 31536000

    # O navegador não manda a URL de onde veio ao sair para outro site — e a
    # URL daqui carrega id de produto e de orçamento.
    SECURE_REFERRER_POLICY = "same-origin"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#: Abaixo desta versão o app instalado mostra "atualize" em vez de abrir
#: (`plataforma.api.versao`). Existe porque a web muda para todos no deploy e
#: o app no bolso da pessoa não: sem este piso, uma mudança de API quebraria o
#: app velho no meio de uma tela, sem dizer por quê.
APP_MINIMO = os.environ.get("FILA_APP_MINIMO", "1.0.0")
